### ISSUE TITLE
Make macro recordable

### ISSUE THREAD

**Issue by hinerm** [thorstenwagner/ij-ridgedetection#13]
I would really like to call this plugin from a macro, recording all parameters so that a dialog does not need to be shown.

@thorstenwagner I spent a few minutes on it this morning but gave up. It is not clear to me what would need to be done to make this nicely macro recordable in the ImageJ 1.x framework.

If you can give me some direction I am willing to do the work. But I looked at other plugins that I know are fully recordable and still couldn't figure it out. :(

Anyway another option would be to just convert to ImageJ 2 where we could use [`@Parameter`](http://imagej.net/Writing_plugins#What_makes_up_the_SciJava_plugin_framework.3F) notation and get rid of the generic dialog and macro language restrictions altogether. I would be happy to work on this as well but only if you are OK moving to IJ2.

Let me know! :)

**Comment by imagejan** [comment]
@hinerm I just tried and macro recording worked as expected:

```javascript
run("Ridge Detection", "line=3.5 high=230 low=87 darkline extend display add sigma=1.50 lower=3.06 upper=7.99");
```
The only issue currently is the duplicate keyword `show` (recorded when you check both *Show junction points* and *Show IDs*) that can be eliminated by [introducing an underscore in one of the labels](https://github.com/thorstenwagner/ij-ridgedetection/blob/master/src/main/java/de/biomedical_imaging/ij/steger/Lines_.java#L197), e.g. *Show_IDs*.

@thorstenwagner Why are you re-implementing `GenericDialogPlus` when you can just use the one included in Fiji (`fiji.util.gui.GenericDialogPlus`)?

That said, I agree that switching to ImageJ2 parameter notation is the preferred solution in the long term, of course.

**Comment by thorstenwagner** [comment]
As I read this issue I thought that this is probably the problem... I've just forgotten to add an underscore.. Sorry!

The reason is that most of my plugins are implemented on the basis of ImageJ.

**Comment by hinerm** [comment]
> I just tried and macro recording worked as expected:

@imagejan odd. It works for me too now. I must have ran the wrong command or had some global state infecting things... the first time I tried it just put a commented out `//run("Ridge Detection");` line in.

In [my tests](https://github.com/hinerm/ij-ridgedetection/commit/854b0eb81b22aa4f513d00596e8f057344b64e14) it isn't recording the overlap resolution method... any thoughts on what I need to do to get that to record and then run properly?

**Comment by imagejan** [comment]
> It works for me too now. I must have ran the wrong command or had some global state infecting things.

@hinerm I previously encountered "premature" recording when a plugin was running a preview and using `IJ` helper functions that trigger the recording before the `GenericDialog` was actually OKed. But I tried with *Preview* activated, and it worked for me with this plugin.

> In my tests it isn't recording the overlap resolution method... any thoughts on what I need to do to get that to record and then run properly?

You'd have to a choice to the plugin dialog for IJ1 to pick it up:

    gd.addChoice("Overlap resolver", String[] choices, "My great OverlapResolver");

and later read it out (which triggers the actual recording):

    String overlapOptionName = gd.getNextChoice();

**Comment by hinerm** [comment]
>and later read it out (which triggers the actual recording):

Thanks @imagejan . This is what I was trying to find. :)

**Comment by thorstenwagner** [comment]
@hinerm The problem was that the method for overlap resolving it not read out in the dialogItemChanged method. It now record nicely.

**Comment by hinerm** [comment]
@thorstenwagner awesome! thank you!
