### ISSUE TITLE
Releasing a new version

### ISSUE THREAD

**Issue by hadim** [thorstenwagner/ij-ridgedetection#31]
@thorstenwagner could you release a new version of the package using the [release-version.sh](https://github.com/scijava/scijava-scripts/blob/master/release-version.sh) script? A git tag will be automatically created and the package will be uploaded to the ImageJ Maven repository.

If you give write access to the repo I can also do it for you.

Thank you.

**Comment by hadim** [comment]
Before doing that you'll need the Travis build at https://travis-ci.org/thorstenwagner/ij-ridgedetection

**Comment by hadim** [comment]
@thorstenwagner If you give the write permission on the repo, I can do that for you.

**Comment by thorstenwagner** [comment]
Hi! I will try your script today!

**Comment by hadim** [comment]
Perfect. Let me know if you need help.

**Comment by hadim** [comment]
Done. The last version 1.4.1 is on Maven: http://maven.imagej.net/#nexus-search;quick~ij_ridge_detect

**Comment by thorstenwagner** [comment]
Thanks @hadim ! At the moment I'm full of work and hardly find time to maintain my old projects. Sorry!

**Comment by hadim** [comment]
It's ok since I am the one who need it the most at the moment.

Le 26 oct. 2017 02:51, "Thorsten Wagner" <notifications@github.com> a
écrit :
