### ISSUE TITLE
Add license header to source files

### ISSUE THREAD

**Issue by hinerm** [thorstenwagner/ij-ridgedetection#6]
It wasn't immediately clear to me how this plugin should be licensed. It's actually really easy to add license info via the [license-maven-plugin](http://www.mojohaus.org/license-maven-plugin/update-file-header-mojo.html) - especially since you already are extending `pom-imagej`

@thorstenwagner if you let me know what the [license](http://imagej.net/Licensing) should be (GPL? BSD?), I can submit a PR that adds the maven configuration.

**Comment by thorstenwagner** [comment]
@hinerm The code was original written by carsten steger in C, I made just the translation to java / imagej and fixed some bugs. He has used the GPL as licence I guess we should keep that?
