### ISSUE TITLE
Consider using SNAPSHOT-based development versions

### ISSUE THREAD

**Issue by hinerm** [thorstenwagner/ij-ridgedetection#7]
I noticed that there are multiple commits on master with the same Maven release version. This can lead your project to be [unreproducible](http://imagej.net/Architecture#Reproducible_builds).

There are many tools and workflows for [managing release cycles](http://imagej.net/Development_Lifecycle#Phases_of_development). I'm happy to discuss pros and cons here or on the forum, if you're interested.

**Comment by hinerm** [comment]
note that the fact that you're using git, maven, and update sites at all is already great. :+1:

**Comment by thorstenwagner** [comment]
@hinerm But would be multiple commits to the maven version 1.1.1-SNAPSHOT not lead to same problems?

**Comment by hinerm** [comment]
@thorstenwagner that is a great question.

The development lifecycle wiki page is intended to answer that question. I [added a section specifically discussing SNAPSHOT coupling](http://imagej.net/Development_Lifecycle#Relationship_with_Maven_SNAPSHOTs) which I hope makes things a bit clearer.

Basically - yes, SNAPSHOT versions are not reproducible. What I intended by this issue is that SNAPSHOT versions would be used for **most** commits - while you are "in development" - and then when you want to upload a new version of ridge detection, you make a single git commit that changes the version to a non-SNAPSHOT.

Then you have a single git commit that is the authoritative "release X.XX.XX" which you can upload for users.

Note that this behavior is also partially enforced by Maven repositories. If someone else wanted to use ridge detection as a maven dependency, for example, then ridge detection would have to be deployed to a repository (such as [maven.imagej.net](http://maven.imagej.net/index.html#welcome)). Maven repos allow SNAPSHOT versions to be overwritten.. but not release versions.

Anyway, let me know if you have more questions. Happy to discuss further!

**Comment by thorstenwagner** [comment]
For next commits I will used SNAPSHOT-base development versions
